services:
  app:
    build: .
    container_name: app
    ports:
      - "127.0.0.1:8080:8080"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
  prometheus:
    image: prom/prometheus:v3.13.4
    container_name: prometheus
    restart: always
    environment:
      - TZ="Europe/Moscow"
      - LANG="ru_RU.UTF-8"
    command:
      -  '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "127.0.0.1:8081:9090"
    volumes:
#      - prometheus:/etc/prometheus
      - ./prometheus_conf:/etc/prometheus
  grafana:
    image: grafana/grafana:13.2.3
    container_name: grafana
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "127.0.0.1:8082:3000"
    volumes:
      - grafana:/var/lib/grafana
      - ./dashbaords/dashboard.json:/var/lib/grafana/dashboards/dashboard.json

volumes:
  grafana:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: $PWD/grafana